[package]
name = "lable"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "*", features = [
  "default",
  "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }

# For image support:
egui_extras = { version = "*", features = ["default", "image", "webp", "gif", "all_loaders"] }
image = { version = "*", features = ["png"] }
env_logger = { version = "*", features = ["auto-color", "humantime"] }
